name: CI
on:
  push:
    branches:
      - main
    tags: ['*']
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        omc-version:
          - 'nightly'
        version:
          - '1.10'
          - '1.12'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v6

      - name: "Set up OpenModelica Compiler"
        uses: OpenModelica/setup-openmodelica@v1.0
        with:
          version: ${{ matrix.omc-version }}
          packages: |
            omc
          libraries: |
            'Modelica 4.1.0'

      - name: "Setup Julia ${{ matrix.version }}-${{ matrix.arch }}"
        uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1

  sanity:
    name: Sanity check - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    permissions:
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: "Set up OpenModelica Compiler"
        uses: OpenModelica/setup-openmodelica@v1.0
        with:
          version: 'nightly'
          packages: |
            omc
          libraries: |
            'Modelica 4.1.0'

      - name: "Setup Julia 1.12-x64"
        uses: julia-actions/setup-julia@v2
        with:
          version: '1.12'
          arch: x64
      - uses: julia-actions/cache@v3
      - uses: julia-actions/julia-buildpkg@v1

      - name: Sanity check ChuaCircuit
        run: |
          julia --project='.' -e '
            using BaseModelicaLibraryTesting
            main(
              library      = "Modelica",
              version      = "4.1.0",
              filter       = "Modelica.Electrical.Analog.Examples.ChuaCircuit"
            )
          '

      - name: Upload test results
        uses: actions/upload-artifact@v7
        with:
          name: sanity-results-${{ matrix.os }}
          path: results/
          if-no-files-found: error
